-- Drop table if it exists to ensure clean slate (and avoid column errors)
DROP TABLE IF EXISTS public.app_settings;

-- Create app_settings table
CREATE TABLE public.app_settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Branding
    app_name text default 'Abu Mafhal Marketplace',
    logo_url text, -- URL to storage
    primary_color text default '#0F172A', -- Default Dark Blue
    secondary_color text default '#3B82F6', -- Default Blue
    
    -- Feature Flags (JSONB for flexibility)
    features jsonb default '{"enable_header": true}'::jsonb,
    
    -- Payment Methods (JSONB)
    payment_methods jsonb default '{"paystack": true, "crypto": true, "manual": true}'::jsonb,
    
    -- Contact / Support
    support_email text,
    support_phone text,

    -- Constraint: Only one row allowed (Singleton pattern)
    is_singleton boolean default true unique check (is_singleton IS TRUE)
);

-- Turn on RLS
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- 1. READ: Everyone (Anon + Authenticated) can read settings
CREATE POLICY "Everyone can read app settings"
ON public.app_settings
FOR SELECT
USING (true);

-- 2. UPDATE: Only Admins can update
-- (Ensure is_admin() function exists and works)
CREATE POLICY "Admins can update app settings"
ON public.app_settings
FOR UPDATE
TO authenticated
USING ( is_admin() )
WITH CHECK ( is_admin() );

-- 3. INSERT: Only Admins (mostly for initial setup)
CREATE POLICY "Admins can insert app settings"
ON public.app_settings
FOR INSERT
TO authenticated
WITH CHECK ( is_admin() );

-- Initial Seed
INSERT INTO public.app_settings (is_singleton, app_name, primary_color, secondary_color, payment_methods)
VALUES (true, 'Abu Mafhal Marketplace', '#0F172A', '#3B82F6', '{"paystack": true, "crypto": true, "manual": true, "flutterwave": false}');

-- Grant permissions for API access
GRANT SELECT ON public.app_settings TO anon, authenticated, service_role;
GRANT UPDATE ON public.app_settings TO authenticated;
GRANT INSERT ON public.app_settings TO authenticated;
